/*Copyright 2009 Stephan Bezoen, http://stephan.acidcats.nlLicensed under the Apache License, Version 2.0 (the "License");you may not use this file except in compliance with the License.You may obtain a copy of the License at   	http://www.apache.org/licenses/LICENSE-2.0Unless required by applicable law or agreed to in writing, softwaredistributed under the License is distributed on an "AS IS" BASIS,WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.See the License for the specific language governing permissions andlimitations under the License.*/package nl.acidcats.yalog.yala {	import fl.controls.CheckBox;
	import fl.controls.UIScrollBar;
	
	import nl.acidcats.yalog.common.Levels;
	import nl.acidcats.yalog.yala.datafilter.IDataFilter;
	import nl.acidcats.yalog.yala.datafilter.LevelFilter;
	import nl.acidcats.yalog.yala.ui.YalogViewer;
	import nl.acidcats.yalog.yala.ui.YalogViewerStatusEvent;
	import nl.acidcats.yalog.yala.ui.table.RowRenderer;
	
	import org.asaplibrary.ui.buttons.BaseButton;
	import org.asaplibrary.ui.buttons.HilightButton;
	
	import flash.display.MovieClip;
	import flash.display.Sprite;
	import flash.display.StageAlign;
	import flash.display.StageScaleMode;
	import flash.events.Event;
	import flash.events.MouseEvent;
	import flash.text.TextFieldAutoSize;
	import flash.text.TextFormat;
	import flash.utils.getQualifiedClassName;			/**	 * Application controller for the Yala application, to be used as document class for Yala.fla.	 */
	public class AppController extends MovieClip {		/** Height of the control bar at the bottome */		private static const CONTROLBAR_HEIGHT : Number = 30;				// stuff on the timeline		public var tBar : MovieClip;		public var tLed : MovieClip;		public var tPauseButton : BaseButton;		public var tClearButton : HilightButton;		public var tCopyButton : HilightButton;		public var tScrollBar : UIScrollBar;
		public var tDebugCB : CheckBox;		public var tInfoCB : CheckBox;		public var tWarnCB : CheckBox;				// message filters		private var mDebugMessageFilter : IDataFilter = new LevelFilter(Levels.DEBUG);		private var mInfoMessageFilter : IDataFilter = new LevelFilter(Levels.INFO);		private var mWarnMessageFilter : IDataFilter = new LevelFilter(Levels.WARN);		// the actual message viewer		private var mYalogViewer : YalogViewer;				/**		 * Constructor		 */		public function AppController () {			initUI();		}
		/**		 * Initialize user interface elements		 */		private function initUI () : void {			// no scaling			stage.scaleMode = StageScaleMode.NO_SCALE;			stage.align = StageAlign.TOP_LEFT;						// listen to resizing events			stage.addEventListener(Event.RESIZE, handleStageResize);						// create container for Yalog viewer			var s : Sprite = addChildAt(new Sprite(), getChildIndex(tScrollBar) - 1) as Sprite;						// create Yalog viewer			mYalogViewer = new YalogViewer(s, stage.stageWidth, tBar.y);			mYalogViewer.addEventListener(YalogViewerStatusEvent._EVENT, handleViewerStatusEvent);			mYalogViewer.setScrollBar(tScrollBar);						// initialize positioning			handleStageResize();						// listen to clicks			addEventListener(MouseEvent.CLICK, handleClick);			// style checkboxes			styleCheckbox(tDebugCB, RowRenderer.COLORS[0], "Debug");
			styleCheckbox(tInfoCB, RowRenderer.COLORS[1], "Info");
			styleCheckbox(tWarnCB, RowRenderer.COLORS[3], "Warn");		}				/**		 * Set styling properties of specified checkbox		 * @param inCheckbox: checkbox to style		 * @param inColor: text color of label		 * @param inText: label text		 */		private function styleCheckbox (inCheckbox : CheckBox, inColor : uint, inText : String) : void {			var tf:TextFormat = new TextFormat();			tf.font = "Arial";			tf.size = 12;			tf.bold = true;			tf.color = inColor;						inCheckbox.textField.autoSize = TextFieldAutoSize.LEFT;			inCheckbox.setStyle("textFormat", tf);						inCheckbox.label = inText;		}		/**		 * Handle status events from YalogViewer		 */				private function handleViewerStatusEvent (e : YalogViewerStatusEvent) : void {			switch (e.subtype) {				case YalogViewerStatusEvent.ACTIVE: tLed.gotoAndStop("activity"); break;				case YalogViewerStatusEvent.INACTIVE: tLed.gotoAndStop("connected"); break;				case YalogViewerStatusEvent.ERROR: tLed.gotoAndStop("error"); break;				case YalogViewerStatusEvent.PAUSED: tLed.gotoAndStop("pause"); break;			}		}		/**		 *	Handle event from stage that it has been resized		 */		private function handleStageResize (e : Event = null) : void {			// ignore zero-height event, sometimes fired when used as Eclipse plugin			if (stage.stageHeight == 0) return;						// pass on size to viewer			mYalogViewer.setSize(stage.stageWidth, stage.stageHeight - CONTROLBAR_HEIGHT);						// reposition and resize some other interface elements			tBar.width = stage.stageWidth;			tBar.y = stage.stageHeight - CONTROLBAR_HEIGHT;						tClearButton.y = stage.stageHeight - tClearButton.height + 2;			tCopyButton.y = stage.stageHeight - tCopyButton.height - 2;			tPauseButton.y = stage.stageHeight - tPauseButton.height + 4;			tLed.y = stage.stageHeight - tLed.height + 2;
			tDebugCB.y = stage.stageHeight - (tDebugCB.height + 2);			tInfoCB.y = stage.stageHeight - (tDebugCB.height + 2);			tWarnCB.y = stage.stageHeight - (tDebugCB.height + 2);
		}				/**		 *	Handle click events		 */		private function handleClick (e : MouseEvent) : void {			switch (e.target) {				case tClearButton: 					mYalogViewer.clear(); 					break; 				case tCopyButton: 					mYalogViewer.copyDataToClipboard(); 					break;				case tPauseButton: 					mYalogViewer.pause(); 					break;				case tDebugCB: 				case tInfoCB: 				case tWarnCB: 					handleLevelCheckboxClick(e.target as CheckBox); 					break;
			}		}				/**		 *	CheckBox handler for level checkboxes		 */		private function handleLevelCheckboxClick (inCheckBox:CheckBox) : void {			if (inCheckBox.selected) { // select filter to remove				switch (inCheckBox) {					case tDebugCB: mYalogViewer.removeFilter(mDebugMessageFilter); break;					case tInfoCB: mYalogViewer.removeFilter(mInfoMessageFilter); break;					case tWarnCB: mYalogViewer.removeFilter(mWarnMessageFilter); break;				}			} else { // select filter to add				switch (inCheckBox) {					case tDebugCB: mYalogViewer.addFilter(mDebugMessageFilter); break;					case tInfoCB: mYalogViewer.addFilter(mInfoMessageFilter); break;					case tWarnCB: mYalogViewer.addFilter(mWarnMessageFilter); break;				}			}		}		override public function toString():String {			return getQualifiedClassName(this);		}	}}
